/* Triangle, pentagonal, and hexagonal numbers 
 * are generated by the following
 * formulae:

 * Triangle     Tn=n(n+1)/2     1, 3, 6, 10, 15, ...
 * Pentagonal   Pn=n(3n-1)/2    1, 5, 12, 22, 35, ...
 * Hexagonal    Hn=n(2n-1)      1, 6, 15, 28, 45, ...
 
 * It can be verified that:
 * T[285] = P[165] = H[143] = 40755.

 * Find the next triangle number that 
 * is also pentagonal and hexagonal. 

 * Project Euler: 45

 * Answer: 1533776805 */

/* Includes */
#include <stdio.h>
#include <math.h>

/* Definitions */
#define START   40755

/* Prototypes */ 
int main();
void init_tri();
int isHexagonal(long x);
int isNatural(double x);
int isPentagonal(long x);

int main()
{
        long tri; 

        for(long n = START + 1; ; n++){

                /* Generate triangular number */
                tri = n* ((n + 1) / 2); 

                if (isPentagonal(tri) && isHexagonal(tri)){
                        break;
                }
        }


        printf("%li\n", tri);

        return 0;
                        
}


/* Checks if a number is pentagonal by
 * taking the inverse function and 
 * checking if it is a natural number */
int isPentagonal(long x)
{
        double p;

        p = (sqrt(24 * x + 1) + 1) / 6;

        return isNatural(p);
}


/* Checks if a number is hexagonal by
 * taking the inverse function and 
 * checking if it is a natural number */
int isHexagonal(long x)
{
        double h;

        h = (sqrt(8 * x + 1) + 1) / 4;

        return isNatural(h);
}


int isNatural(double x)
{
        return (floorf(x) == x);
}
